version: '2.1'
services:
    api:
        volumes:
            - "${SOURCE_DIR}/backend-api:/src"
            - "${SOURCE_DIR}/module-lucius:/module-lucius"
            - "${SOURCE_DIR}/module-logger:/module-logger"
            - "${SOURCE_DIR}/module-service-factory:/module-service-factory"
            - "${SOURCE_DIR}/module-util:/module-util"
        env_file:
            - ${SERVICE_DIR}/backend-api/.env
            - ./.env
        ports:
            - "127.0.0.1:${API_EXPOSED_PORT}:${API_PORT}"
            - "127.0.0.1:${DEBUG_EXPOSED_PORT_API}:${DEBUG_PORT}"
        links:
            - auth
            - db
        build:
            context: .
            dockerfile: Dockerfile-node
    auth:
        volumes:
            - "${SOURCE_DIR}/backend-auth:/src"
            - "${SOURCE_DIR}/module-lucius:/module-lucius"
            - "${SOURCE_DIR}/module-logger:/module-logger"
            - "${SOURCE_DIR}/module-service-factory:/module-service-factory"
            - "${SOURCE_DIR}/module-util:/module-util"
        env_file:
            - ${SERVICE_DIR}/backend-auth/.env
            - ./.env
        ports:
            - "127.0.0.1:${DEBUG_EXPOSED_PORT_AUTH}:${DEBUG_PORT}"
        links:
            - db
        build:
            context: .
            dockerfile: Dockerfile-node
    db:
        volumes:
            - "${SOURCE_DIR}/backend-db:/src"
            - "${SOURCE_DIR}/module-lucius:/module-lucius"
            - "${SOURCE_DIR}/module-logger:/module-logger"
            - "${SOURCE_DIR}/module-service-factory:/module-service-factory"
            - "${SOURCE_DIR}/module-util:/module-util"
        env_file:
            - ${SERVICE_DIR}/backend-db/.env
            - ./.env
        ports:
            - "127.0.0.1:${DEBUG_EXPOSED_PORT_DB}:${DEBUG_PORT}"
        links:
            - couchdb
            - geo
        build:
            context: .
            dockerfile: Dockerfile-node
    geo:
        volumes:
            - "${SOURCE_DIR}/backend-geo:/src"
            - "${SOURCE_DIR}/module-lucius:/module-lucius"
            - "${SOURCE_DIR}/module-logger:/module-logger"
            - "${SOURCE_DIR}/module-service-factory:/module-service-factory"
            - "${SOURCE_DIR}/module-util:/module-util"
        env_file:
            - ${SERVICE_DIR}/backend-geo/.env
            - ./.env
        ports:
            - "127.0.0.1:${DEBUG_EXPOSED_PORT_GEO}:${DEBUG_PORT}"
        build:
            context: .
            dockerfile: Dockerfile-node
    couchdb:
        env_file:
            - ${SERVICE_DIR}/couchdb/.env
            - ./.env
        image: registry.ops.worldcleanupday.com/couchdb_geocouch:latest
        ports:
            - "127.0.0.1:5984:5984"
        volumes:
            - ./services/couchdb/db:/usr/local/var/lib/couchdb
            - ./services/couchdb/etc/local.ini:/usr/local/etc/couchdb/local.ini
